[PLObfuAmZm9pAgvtZ1cEHbEHKqp9D3ePHS]
name = "Game Changer (${ALL_SEASONS})"
show = "Game Changer"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (trailers and behind-the-scenes videos) from ${SEASONS} seasons of Game Changer, the only game show where the game changes every show. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pBtHSq5HewgAKihMK6kaeJS]
name = "Um, Actually (${ALL_SEASONS})"
show = "Um, Actually"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (trailers and behind-the-scenes videos) from ${SEASONS} seasons of Um Actually, the game show where nerds correct nerds. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pBIEdqpWKGZXaUroUOThmmJ]
name = "Breaking News / No Laugh Newsroom (${ALL_SEASONS})"
show = "Breaking News"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} trailers from ${SEASONS} seasons of Breaking News / No Laugh Newsroom: in this newsroom, breaking means losing. Our reporters don't know what's about to be on the teleprompter, and every laugh is a point against them. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pDfm8v_2TRx_GSpV43ABXsM]
name = "Make Some Noise (${ALL_SEASONS})"
show = "Make Some Noise"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} trailers from ${SEASONS} seasons of Make Some Noise, a game show where talented contestants compete to bring to life silly prompts. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pDfejgejY4h6r06blOLedPl]
name = "Dirty Laundry (${ALL_SEASONS})"
show = "Dirty Laundry"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} trailers from ${SEASONS} seasons of Dirty Laundry, a show where guests tell secrets, guess who they belong to, and enjoy a few drinks. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pCsCC1Vkjb6hV6Vvew3z-Z_]
name = "Play It By Ear (${ALL_SEASONS})"
show = "Play It By Ear"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} trailers from ${SEASONS} seasons of Play It By Ear, a musical improv show where players craft an original musical out of thin air and silly prompts. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pCDFLc4eTkdFoMy5qW5pqW9]
name = "Very Important People (${ALL_SEASONS})"
show = "Very Important People"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} trailers from Very Important People, a show where comedians are given makeovers to be transformed into someone completely new, and then have a fully-improvised interview with host Vic Michaelis. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pC4WERMgeEPlWLuLXIidDjr]
name = "Smartypants (${ALL_SEASONS})"
show = "Smartypants"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} trailers from Smartypants. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pCDwDKLDD8-UBsNRXKEOFHu]
name = "Thousandaires (${ALL_SEASONS})"
show = "Thousandaires"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} trailers from Thousandaires. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pDZr7wOZPq0eCDbOIyD1IU2]
name = "Dropout Presents (${ALL_SEASONS})"
show = "Dropout Presents"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} trailers from Dropout Presents. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pArudk1FiNVZhEE9iNiUJny]
name = "Monét's Slumber Party (${ALL_SEASONS})"
show = "Monét's Slumber Party"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} trailers from Monét's Slumber Party. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pBkN8f2QDbVcfRpjaOdPLwY]
name = "Gastronauts (${ALL_SEASONS})"
show = "Gastronauts"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} trailers from Gastronauts. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pDMHtb0drlb8b6hC3FG_A5r]
name = "Adventuring Academy (${ALL_SEASONS})"
show = "Adventuring Academy"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes from ${SEASONS} seasons of Adventuring Academy, a show where veteran gamemaster Brennan Lee Mulligan dives deep into role-playing games, with tips for everyone from first-time players to other pros. ${MAYBE_MEMBERS_ONLY}
"""

[PLObfuAmZm9pD9kA_rvjirtpBUtwdthWmD]
name = "Dimension 20 (${ALL_SEASONS})"
show = "Dimension 20"
type = ["episode", "special", "bts", "trailer"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (behind-the-scenes videos, talkback shows, and trailers) from ${SEASONS} seasons of Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pDqgg3_8kXgd7uFrOFmGVUG]
name = "Dimension 20 (${ALL_EPISODES})"
show = "Dimension 20"
type = ["episode", "special"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes of from ${SEASONS} seasons of Dimension 20 in order. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pA-p-uZkuEdt-xqzVMCqSGO]
name = "Dimension 20 (${EPISODES} Free Episodes)"
show = "Dimension 20"
type = ["episode", "special"]
free = true
description = """
${HOURS}-hour playlist of free episodes of Dimension 20.

${D20_PLUG}
"""

[PLObfuAmZm9pBlmfWjeRYUmsucnZo87ONA]
name = "Dimension 20 (${EPISODES} Free Episodes and ${EXTRAS} Free Extras)"
show = "Dimension 20"
type = ["episode", "special", "bts", "trailer"]
free = true
description = """
${HOURS}-hour playlist ${EPISODES} free episodes of Dimension 20 and ${EXTRAS} free extras (behind-the-scenes videos, talkback shows, and trailers).

${D20_PLUG}
"""

[PLObfuAmZm9pBUEjI0SyuAQnSWKvcUI62R]
name = "Dimension 20: Fantasy High (${ALL_SEASONS})"
show = "Dimension 20"
cast = "Intrepid Heroes"
world = "Spyre"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from ${SEASONS} seasons of Fantasy High, a series of campaigns from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pCvvl_cPBxZZ1l0XHWHgez6]
name = "Dimension 20: The Unsleeping City (${ALL_SEASONS})"
show = "Dimension 20"
cast = "Intrepid Heroes"
world = "The Unsleeping City"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from ${SEASONS} seasons of The Unsleeping City, a series of campaigns from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pCkRpIn_Z8BgV4h06DSgvOQ]
skip = true
name = "Dimension 20: Escape from the Bloodkeep (${ALL_SEASONS})"
show = "Dimension 20"
season = "Escape from the Bloodkeep"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Escape from the Bloodkeep, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pCn84dZNnZcJTgnCoWtnteU]
skip = true
name = "Dimension 20: Tiny Heist (${ALL_SEASONS})"
show = "Dimension 20"
season = "Tiny Heist"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Tiny Heist, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pD_zyHeSfr-PtYJ31lW0k0B]
skip = true
name = "Dimension 20: A Crown of Candy (${ALL_SEASONS})"
show = "Dimension 20"
season = "A Crown of Candy"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from A Crown of Candy, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pC6DqGsIuQQhNCyeTMlHMu4]
skip = true
name = "Dimension 20: Pirates of Leviathan (${ALL_SEASONS})"
show = "Dimension 20"
season = "Pirates of Leviathan"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Pirates of Leviathan, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pCWF7V_iu5LZVZEs1UUyiPm]
skip = true
name = "Dimension 20: Mice and Murder (${ALL_SEASONS})"
show = "Dimension 20"
season = "Mice and Murder"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Mice and Murder, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pAB72I23WBd5L3WVkR38cnz]
skip = true
name = "Dimension 20: Misfits and Magic (${ALL_SEASONS})"
show = "Dimension 20"
season = "Misfits and Magic"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Misfits and Magic, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pA3CGZsq0i1cWWHcC-2mYp7]
skip = true
name = "Dimension 20: The Seven (${ALL_SEASONS})"
show = "Dimension 20"
season = "The Seven"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from The Seven, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pDLiMGbBWJtqXV9Z7o6TrxY]
skip = true
name = "Dimension 20: Shriek Week (${ALL_SEASONS})"
show = "Dimension 20"
season = "Shriek Week"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Shriek Week, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pCQbgg-V2SlQBm9TNucLth4]
skip = true
name = "Dimension 20: A Starstruck Odyssey (${ALL_SEASONS})"
show = "Dimension 20"
season = "A Starstruck Odyssey"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from A Starstruck Odyssey, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pDuTXqGVHBjky_s9Je5F1t7]
skip = true
name = "Dimension 20: Coffin Run (${ALL_SEASONS})"
show = "Dimension 20"
season = "Coffin Run"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Coffin Run, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pCWj6M5fxATywmOeAg4zlTF]
skip = true
name = "Dimension 20: A Court of Fey and Flowers (${ALL_SEASONS})"
show = "Dimension 20"
season = "A Court of Fey and Flowers"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from A Court of Fey and Flowers, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pDkoJ-w4PJ6KOroEFTVQVvS]
skip = true
name = "Dimension 20: Neverafter (${ALL_SEASONS})"
show = "Dimension 20"
season = "Neverafter"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Neverafter, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pATr-wPPLwMGFCLdMb74ID3]
skip = true
name = "Dimension 20: The Ravening War (${ALL_SEASONS})"
show = "Dimension 20"
season = "The Ravening War"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from The Ravening War, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pA8zs8-4LcmeA8m494S6Qhr]
skip = true
name = "Dimension 20: Dungeons and Drag Queens (${ALL_SEASONS})"
show = "Dimension 20"
season = "Dungeons and Drag Queens"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Dungeons and Drag Queens, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pC-aZMoB4n8QrySHWncIiLb]
skip = true
name = "Dimension 20: Mentopolis (${ALL_SEASONS})"
show = "Dimension 20"
season = "Mentopolis"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Mentopolis, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pCXX8ABGmvnd9oWo3JXrCUS]
skip = true
name = "Dimension 20: Burrow's End (${ALL_SEASONS})"
show = "Dimension 20"
season = "Burrow's End"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Burrow's End, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pBjNu14Cp6kX1E0JmUHmoaS]
name = "Dimension 20: Never Stop Blowing Up (${ALL_SEASONS})"
show = "Dimension 20"
season = "Never Stop Blowing Up"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, behind-the-scenes videos, and interviews) from Never Stop Blowing Up, a campaign from Dimension 20. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pByRsqyhiiNqjUCeJYSejZb]
name = "Dimension 20: Intrepid Heroes (${ALL_SEASONS})"
show = "Dimension 20"
cast = "Intrepid Heroes"
type = ["episode", "special", "bts", "trailer"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, and behind-the-scenes videos) from ${SEASONS} seasons of Dimension 20 which feature the Intrepid Heroes cast. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pANHp2gvo0ZVsEhJtdcbccB]
name = "Dimension 20: Spyre (${ALL_SEASONS})"
show = "Dimension 20"
world = "Spyre"
type = ["episode", "special", "bts", "trailer"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, and behind-the-scenes videos) from ${SEASONS} seasons of Dimension 20 set in the world of Spyre. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pDew7JTMNzlRYE-gwEo5WYt]
name = "Dimension 20: Calorum (${ALL_SEASONS})"
show = "Dimension 20"
world = "Calorum"
type = ["episode", "special", "bts", "trailer"]
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras (talkbacks, trailers, and behind-the-scenes videos) from ${SEASONS} seasons of Dimension 20 set in the world of Calorum. ${MAYBE_MEMBERS_ONLY}

${D20_PLUG}
"""

[PLObfuAmZm9pCvSRFDmMNWoWva8kEIPXH1]
skip = true
name = "Critical Role: Exandria Unlimited: Calamity (${ALL_SEASONS})"
show = "Critical Role"
season = "Exandria Unlimited: Calamity"
description = """
${HOURS}-hour playlist of ${EPISODES} episodes and ${EXTRAS} extras from Exandria Unlimited: Calamity, a Critical Role campaign.
"""

[PLObfuAmZm9pAtGx3ED2spFfabR30tKcSq]
skip = true
name = "Bluey (for Canadians)"
show = "Bluey"
description = """
${HOURS}-hour playlist of episodes and shorts from Bluey. ${FREE} videos are free and ${PAID} can be purchased in Canada.
"""
