[PLObfuAmZm9pAgvtZ1cEHbEHKqp9D3ePHS]
name = "Game Changer (All 6 Seasons)"
show = "Game Changer"
description = """
${HOURS}-hour playlist of all episodes, trailers, and behind-the-scenes videos from Game Changer, the only game show where the game changes every show.
"""

[PLObfuAmZm9pBtHSq5HewgAKihMK6kaeJS]
name = "Um, Actually (All 9 Seasons)"
show = "Um, Actually"
description = """
${HOURS}-hour playlist of all episodes, trailers, and behind-the-scenes videos from Um Actually, the game show where nerds correct nerds.
"""

[PLObfuAmZm9pBIEdqpWKGZXaUroUOThmmJ]
skip = true
name = "Breaking News (All 6 Seasons)"
show = "Breaking News"
description = """
${HOURS}-hour playlist of all episodes and trailers videos from Breaking News: in this newsroom, breaking means losing. Our reporters don't know what's about to be on the teleprompter, and every laugh is a point against them.
"""

[PLObfuAmZm9pDfm8v_2TRx_GSpV43ABXsM]
name = "Make Some Noise (All 2 Seasons)"
show = "Make Some Noise"
description = """
${HOURS}-hour playlist of all episodes and trailers from Make Some Noise, a game show where talented contestants compete to bring to life silly prompts.
"""

[PLObfuAmZm9pDfejgejY4h6r06blOLedPl]
skip = true
name = "Dirty Laundry (All 4 Seasons)"
show = "Dirty Laundry"
description = """
${HOURS}-hour playlist of all episodes and trailers videos from Dirty Laundry.
"""

[PLObfuAmZm9pCsCC1Vkjb6hV6Vvew3z-Z_]
name = "Play It By Ear (All 2 Seasons)"
show = "Play It By Ear"
description = """
${HOURS}-hour playlist of all episodes and trailers from Play It By Ear, a musical improv show where players craft an original musical out of thin air and silly prompts.
"""

[PLObfuAmZm9pCDFLc4eTkdFoMy5qW5pqW9]
skip = true
name = "Very Important People (All Episodes and Extras)"
show = "Very Important People"
description = """
${HOURS}-hour playlist of all episodes and trailers videos from Very Important People.
"""

[PLObfuAmZm9pDMHtb0drlb8b6hC3FG_A5r]
skip = true
name = "Adventuring Academy (All Seasons)"
show = "Adventuring Academy"
description = """
${HOURS}-hour playlist of all episodes and trailers videos from Adventuring Academy.
"""

[PLObfuAmZm9pD9kA_rvjirtpBUtwdthWmD]
name = "Dimension 20 (All 21 Seasons)"
show = "Dimension 20"
type = ["episode", "special", "bts", "trailer"]
description = """
${HOURS}-hour playlist of every episode of Dimension 20 and all associated extra content, such as behind-the-scenes videos, talkback shows, and trailers. Free videos are used where possible, and member-only videos used for the rest. Episodes are grouped by seasons, with trailers coming first and extra content coming after the episode or season it refers to.

${D20_PLUG}
"""

[PLObfuAmZm9pDqgg3_8kXgd7uFrOFmGVUG]
name = "Dimension 20 (All Episodes)"
show = "Dimension 20"
type = ["episode", "special"]
description = """
${HOURS}-hour playlist of every episode of Dimension 20 in order. Free videos are used where possible, and member-only videos used for the rest. Episodes are all in chronological release order, except for special live episodes, with are grouped with their associated seasons even if they occurred a bit later.

${D20_PLUG}
"""

[PLObfuAmZm9pA-p-uZkuEdt-xqzVMCqSGO]
name = "Dimension 20 (Free Episodes)"
show = "Dimension 20"
type = ["episode", "special"]
free = true
description = """
${HOURS}-hour playlist of all free episodes of Dimension 20.

${D20_PLUG}
"""

[PLObfuAmZm9pBlmfWjeRYUmsucnZo87ONA]
name = "Dimension 20 (Free Episodes and Extras)"
show = "Dimension 20"
type = ["episode", "special", "bts", "trailer"]
free = true
description = """
${HOURS}-hour playlist of all free episodes of Dimension 20 and all free extra content, such as behind-the-scenes videos, talkback shows, and trailers. Episodes are grouped by seasons, with trailers coming first and extra content coming after the episode or season it refers to.

${D20_PLUG}
"""


[PLObfuAmZm9pBUEjI0SyuAQnSWKvcUI62R]
name = "Dimension 20: Fantasy High (All 3 Seasons)"
show = "Dimension 20"
cast = "Intrepid Heroes"
world = "Spyre"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from all seasons of Fantasy High, a series of campaigns from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pCvvl_cPBxZZ1l0XHWHgez6]
name = "Dimension 20: The Unsleeping City (All 2 Seasons)"
show = "Dimension 20"
cast = "Intrepid Heroes"
world = "The Unsleeping City"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from all seasons of The Unsleeping City, a series of campaigns from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pCkRpIn_Z8BgV4h06DSgvOQ]
skip = true
name = "Dimension 20: Escape from the Bloodkeep (Episodes and Extras)"
show = "Dimension 20"
season = "Escape from the Bloodkeep"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from Escape from the Bloodkeep, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pCn84dZNnZcJTgnCoWtnteU]
skip = true
name = "Dimension 20: Tiny Heist (Episodes and Extras)"
show = "Dimension 20"
season = "Tiny Heist"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from Tiny Heist, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pD_zyHeSfr-PtYJ31lW0k0B]
skip = true
name = "Dimension 20: A Crown of Candy (Episodes and Extras)"
show = "Dimension 20"
season = "A Crown of Candy"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from A Crown of Candy, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pC6DqGsIuQQhNCyeTMlHMu4]
skip = true
name = "Dimension 20: Pirates of Leviathan (Episodes and Extras)"
show = "Dimension 20"
season = "Pirates of Leviathan"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from Pirates of Leviathan, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pCWF7V_iu5LZVZEs1UUyiPm]
skip = true
name = "Dimension 20: Mice and Murder (Episodes and Extras)"
show = "Dimension 20"
season = "Mice and Murder"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from Mice and Murder, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pAB72I23WBd5L3WVkR38cnz]
skip = true
name = "Dimension 20: Misfits and Magic (Episodes and Extras)"
show = "Dimension 20"
season = "Misfits and Magic"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from Misfits and Magic, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pA3CGZsq0i1cWWHcC-2mYp7]
skip = true
name = "Dimension 20: The Seven (Episodes and Extras)"
show = "Dimension 20"
season = "The Seven"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from The Seven, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pDLiMGbBWJtqXV9Z7o6TrxY]
skip = true
name = "Dimension 20: Shriek Week (Episodes and Extras)"
show = "Dimension 20"
season = "Shriek Week"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from Shriek Week, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pCQbgg-V2SlQBm9TNucLth4]
skip = true
name = "Dimension 20: A Starstruck Odyssey (Episodes and Extras)"
show = "Dimension 20"
season = "A Starstruck Odyssey"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from A Starstruck Odyssey, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pDuTXqGVHBjky_s9Je5F1t7]
skip = true
name = "Dimension 20: Coffin Run (Episodes and Extras)"
show = "Dimension 20"
season = "Coffin Run"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from Coffin Run, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pCWj6M5fxATywmOeAg4zlTF]
skip = true
name = "Dimension 20: A Court of Fey and Flowers (Episodes and Extras)"
show = "Dimension 20"
season = "A Court of Fey and Flowers"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from A Court of Fey and Flowers, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pDkoJ-w4PJ6KOroEFTVQVvS]
skip = true
name = "Dimension 20: Neverafter (Episodes and Extras)"
show = "Dimension 20"
season = "Neverafter"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from Neverafter, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pATr-wPPLwMGFCLdMb74ID3]
skip = true
name = "Dimension 20: The Ravening War (Episodes and Extras)"
show = "Dimension 20"
season = "The Ravening War"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from The Ravening War, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pA8zs8-4LcmeA8m494S6Qhr]
skip = true
name = "Dimension 20: Dungeons and Drag Queens (Episodes and Extras)"
show = "Dimension 20"
season = "Dungeons and Drag Queens"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from Dungeons and Drag Queens, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pC-aZMoB4n8QrySHWncIiLb]
skip = true
name = "Dimension 20: Mentopolis (Episodes and Extras)"
show = "Dimension 20"
season = "Mentopolis"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from Mentopolis, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pCXX8ABGmvnd9oWo3JXrCUS]
name = "Dimension 20: Burrow's End (Episodes and Extras)"
show = "Dimension 20"
season = "Burrow's End"
type = ["episode", "special", "bts", "trailer", "external"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, behind-the-scenes videos, and third-party interviews from Burrow's End, a campaign from Dimension 20. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""


[PLObfuAmZm9pByRsqyhiiNqjUCeJYSejZb]
name = "Dimension 20: Intrepid Heroes (All 8 Seasons)"
show = "Dimension 20"
cast = "Intrepid Heroes"
type = ["episode", "special", "bts", "trailer"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, and behind-the-scenes from all seasons of Dimension 20 which star the core Intrepid Heroes cast. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pANHp2gvo0ZVsEhJtdcbccB]
name = "Dimension 20: Spyre (All 5 Seasons)"
show = "Dimension 20"
world = "Spyre"
type = ["episode", "special", "bts", "trailer"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, and behind-the-scenes from all seasons of Dimension 20 set in the world of Spyre. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""

[PLObfuAmZm9pDew7JTMNzlRYE-gwEo5WYt]
name = "Dimension 20: Calorum (All 2 Seasons)"
show = "Dimension 20"
world = "Calorum"
type = ["episode", "special", "bts", "trailer"]
description = """
${HOURS}-hour playlist of all episodes, talkbacks, trailers, and behind-the-scenes from all seasons of Dimension 20 set in the world of Calorum. Free videos are used where possible, and member-only videos used for the rest.

${D20_PLUG}
"""


[PLObfuAmZm9pCvSRFDmMNWoWva8kEIPXH1]
skip = true
name = "Critical Role: Exandria Unlimited: Calamity (Episodes and Extras)"
show = "Critical Role"
season = "Exandria Unlimited: Calamity"
description = """
${HOURS}-hour playlist of all episodes and extras from Exandria Unlimited: Calamity, a Critical Role campaign.
"""
