[dropout]
incremental-interval = "PT4M"
complete-interval = "P16D"

[dimension20show]
incremental-interval = "PT32M"
complete-interval = "P64D"

[dimension20shorts]
incremental-interval = "PT32M"
complete-interval = "P64D"

[umactually]
incremental-interval = "PT8H"
complete-interval = "P64D"

[gamechangershorts]
incremental-interval = "PT8H"
complete-interval = "P64D"

[makesomenoisedo]
incremental-interval = "PT8H"
complete-interval = "P64D"

[dirtylaundryshorts]
incremental-interval = "PT8H"
complete-interval = "P64D"

[veryimportantpeopleshow]
incremental-interval = "PT8H"
complete-interval = "P64D"

[blueyofficialchannel]
incremental-interval = "P4D"
complete-interval = "P128D"

[deepblueink]
incremental-interval = "P4D"
complete-interval = "P128D"

[screenrantplus]
incremental-interval = "P4D"
complete-interval = "P128D"

[geek_peek]
incremental-interval = "P4D"
complete-interval = "P128D"

[thejordonbrown]
incremental-interval = "P4D"
complete-interval = "P128D"

[worldsbeyondnumber]
incremental-interval = "P12D"
complete-interval = "P128D"

[samreich]
incremental-interval = "P12D"
complete-interval = "P128D"

[blueyfrancais]
incremental-interval = "P16D"
complete-interval = "P128D"

[thewelltoldtale]
incremental-interval = "P16D"
complete-interval = "P128D"

["channel/UCbwnaOxVtqUWmeJsdKTlqfg"]
incremental-interval = "P32D"
complete-interval = "P32D"

[naddpod]
incremental-interval = "P32D"
complete-interval = "P128D"

[characterswelcome]
incremental-interval = "P128D"
complete-interval = "P256D"

[roll20app]
incremental-interval = "P128D"
complete-interval = "P256D"

[criticalrole]
incremental-interval = "P128D"
complete-interval = "P256D"

[siblingrivalrypodcast]
incremental-interval = "P128D"
complete-interval = "P256D"

[hankschannel]
incremental-interval = "P128D"
complete-interval = "P256D"

[rickastleyyt]
incremental-interval = "P128D"
complete-interval = "P256D"

[geekandsundry]
incremental-interval = "P128D"
complete-interval = "P256D"

[themcelroyfamily]
incremental-interval = "P128D"
complete-interval = "P256D"
