[dropout]
min-interval = "PT32M"

[dimension20show]
min-interval = "PT32M"

[dimension20shorts]
min-interval = "PT32M"

[umactually]
min-interval = "PT8H"

[gamechangershorts]
min-interval = "PT8H"

[makesomenoisedo]
min-interval = "PT8H"

[dirtylaundryshorts]
min-interval = "PT8H"

[veryimportantpeopleshow]
min-interval = "PT8H"

[deepblueink]
template = "P2D"

[screenrantplus]
template = "P4D"

[geek_peek]
template = "P4D"

[thejordonbrown]
template = "P4D"

[worldsbeyondnumber]
min-interval = "P12D"

[samreich]
min-interval = "P12D"

[blueyofficialchannel]
min-interval = "P16D"

[blueyfrancais]
min-interval = "P16D"

[thewelltoldtale]
min-interval = "P16D"

[naddpod]
min-interval = "P32D"

[rickastleyyt]
min-interval = "P128D"
