[dropout]
incremental-interval = "PT4M"
complete-interval = "P128D"

[dimension20show]
incremental-interval = "PT32M"
complete-interval = "P128D"

[dimension20shorts]
incremental-interval = "PT32M"
complete-interval = "P128D"

[umactually]
incremental-interval = "PT8H"
complete-interval = "P128D"

[gamechangershorts]
incremental-interval = "PT8H"
complete-interval = "P128D"

[makesomenoisedo]
incremental-interval = "PT8H"
complete-interval = "P128D"

[dirtylaundryshorts]
incremental-interval = "PT8H"
complete-interval = "P128D"

[veryimportantpeopleshow]
incremental-interval = "PT8H"
complete-interval = "P128D"

[blueyofficialchannel]
incremental-interval = "P1D"
complete-interval = "P8D"

[rarran]
incremental-interval = "P2000D"
complete-interval = "P128000D"

[covertgoblue]
incremental-interval = "P2000D"
complete-interval = "P128000D"

[deepblueink]
incremental-interval = "P4000D"
complete-interval = "P128000D"

[worldsbeyondnumber]
incremental-interval = "P12000D"
complete-interval = "P128000D"

[samreich]
incremental-interval = "P12000D"
complete-interval = "P128000D"

[blueyfrancais]
incremental-interval = "P16000D"
complete-interval = "P128000D"

["$blueycanada"]
incremental-interval = "P32000D"
complete-interval = "P32000D"

[naddpod]
incremental-interval = "P32000D"
complete-interval = "P128000D"

[screenrantplus]
incremental-interval = "P57000D"
complete-interval = "P128000D"

[geek_peek]
incremental-interval = "P58000D"
complete-interval = "P128000D"

[thejordonbrown]
incremental-interval = "P59000D"
complete-interval = "P128000D"

[loadingreadyrun]
incremental-interval = "P60000D"
complete-interval = "P260000D"

[characterswelcome]
incremental-interval = "P61000D"
complete-interval = "P261000D"

[dorkly]
incremental-interval = "P62000D"
complete-interval = "P262000D"

[thewelltoldtale]
incremental-interval = "P63000D"
complete-interval = "P263000D"

[drawfee]
incremental-interval = "P64000D"
complete-interval = "P264000D"

[roll20app]
incremental-interval = "P65000D"
complete-interval = "P265000D"

[criticalrole]
incremental-interval = "P66000D"
complete-interval = "P266000D"

[siblingrivalrypodcast]
incremental-interval = "P67000D"
complete-interval = "P267000D"

[hankschannel]
incremental-interval = "P68000D"
complete-interval = "P268000D"

[rickastleyyt]
incremental-interval = "P69000D"
complete-interval = "P269000D"

[geekandsundry]
incremental-interval = "P70000D"
complete-interval = "P270000D"

[themcelroyfamily]
incremental-interval = "P71000D"
complete-interval = "P271000D"

[ryangeorge]
incremental-interval = "P72000D"
complete-interval = "P272000D"

[joel-haver]
incremental-interval = "P73000D"
complete-interval = "P273000D"

[genericallyentertaining]
incremental-interval = "P74000D"
complete-interval = "P274000D"

[blumineck]
incremental-interval = "P75000D"
complete-interval = "P275000D"

[briandavidgilbert]
incremental-interval = "P76000D"
complete-interval = "P276000D"

[dndwizards]
incremental-interval = "P77000D"
complete-interval = "P277000D"

[mancarryingthing]
incremental-interval = "P78000D"
complete-interval = "P278000D"

[indeepgeek]
incremental-interval = "P79000D"
complete-interval = "P279000D"

[highrollersdnd]
incremental-interval = "P80000D"
complete-interval = "P280000D"

[arcanearcade]
incremental-interval = "P81000D"
complete-interval = "P281000D"

[dndbeyond]
incremental-interval = "P82000D"
complete-interval = "P282000D"

[dungeonsanddaddies]
incremental-interval = "P83000D"
complete-interval = "P283000D"

[stinkydragonpod]
incremental-interval = "P84000D"
complete-interval = "P284000D"

[pitchmeetings]
incremental-interval = "P85000D"
complete-interval = "P285000D"

[pulpcomedy]
incremental-interval = "P86000D"
complete-interval = "P286000D"

[julienolke]
incremental-interval = "P87000D"
complete-interval = "P287000D"

[zacoyama]
incremental-interval = "P88000D"
complete-interval = "P288000D"

[pitchmeetingshorts]
incremental-interval = "P89000D"
complete-interval = "P289000D"

[ryangeorgeplus]
incremental-interval = "P90000D"
complete-interval = "P290000D"

[idglive]
incremental-interval = "P91000D"
complete-interval = "P291000D"

[acquisitionsincorporated]
incremental-interval = "P92000D"
complete-interval = "P292000D"

[legomastersfox]
incremental-interval = "P93000D"
complete-interval = "P293000D"

[taylortomlinsoncomedy]
incremental-interval = "P94000D"
complete-interval = "P294000D"
