[dropout]
incremental-interval = "PT4M"
complete-interval = "P16D"

[dimension20show]
incremental-interval = "PT32M"
complete-interval = "P24D"

[dimension20shorts]
incremental-interval = "PT32M"
complete-interval = "P24D"

[umactually]
incremental-interval = "PT8H"
complete-interval = "P24D"

[gamechangershorts]
incremental-interval = "PT8H"
complete-interval = "P24D"

[makesomenoisedo]
incremental-interval = "PT8H"
complete-interval = "P24D"

[dirtylaundryshorts]
incremental-interval = "PT8H"
complete-interval = "P24D"

[veryimportantpeopleshow]
incremental-interval = "PT8H"
complete-interval = "P24D"

[deepblueink]
incremental-interval = "P2D"
complete-interval = "P128D"

[screenrantplus]
incremental-interval = "P4D"
complete-interval = "P128D"

[geek_peek]
incremental-interval = "P4D"
complete-interval = "P128D"

[thejordonbrown]
incremental-interval = "P4D"
complete-interval = "P128D"

[worldsbeyondnumber]
incremental-interval = "P12D"
complete-interval = "P128D"

[samreich]
incremental-interval = "P12D"
complete-interval = "P128D"

[blueyofficialchannel]
incremental-interval = "P16D"
complete-interval = "P128D"

[blueyfrancais]
incremental-interval = "P16D"
complete-interval = "P128D"

[thewelltoldtale]
incremental-interval = "P16D"
complete-interval = "P128D"

[naddpod]
incremental-interval = "P32D"
complete-interval = "P128D"

[Roll20App]
incremental-interval = "P128Y"
complete-interval = "P128Y"

[criticalrole]
incremental-interval = "P128Y"
complete-interval = "P128Y"

[siblingrivalrypodcast]
incremental-interval = "P128Y"
complete-interval = "P128Y"

[hankschannel]
incremental-interval = "P128Y"
complete-interval = "P128Y"

[rickastleyyt]
incremental-interval = "P128Y"
complete-interval = "P128Y"
