[dropout]
incremental-interval = "PT4M"
complete-interval = "P7D"

[dimension20show]
incremental-interval = "PT32M"
complete-interval = "P32D"

[dimension20shorts]
incremental-interval = "PT32M"
complete-interval = "P32D"

[umactually]
incremental-interval = "PT8H"
complete-interval = "P32D"

[gamechangershorts]
incremental-interval = "PT8H"
complete-interval = "P32D"

[makesomenoisedo]
incremental-interval = "PT8H"
complete-interval = "P32D"

[dirtylaundryshorts]
incremental-interval = "PT8H"
complete-interval = "P32D"

[veryimportantpeopleshow]
incremental-interval = "PT8H"
complete-interval = "P32D"

[thousandairesdo]
incremental-interval = "PT8H"
complete-interval = "P32D"

[dropoutpresents]
incremental-interval = "PT8H"
complete-interval = "P32D"

[smartypantsdropout]
incremental-interval = "PT8H"
complete-interval = "P32D"

[monetsslumberparty]
incremental-interval = "PT8H"
complete-interval = "P32D"

[rarran]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[covertgoblue]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[blueyofficialchannel]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[deepblueink]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[worldsbeyondnumber]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[samreich]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[blueyfrancais]
incremental-interval = "P99999D"
complete-interval = "P99999D"

["$blueycanada"]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[naddpod]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[screenrantplus]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[geek_peek]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[thejordonbrown]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[loadingreadyrun]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[characterswelcome]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[dorkly]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[thewelltoldtale]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[drawfee]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[roll20app]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[criticalrole]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[siblingrivalrypodcast]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[hankschannel]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[rickastleyyt]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[geekandsundry]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[themcelroyfamily]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[briandavidgilbert]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[dndwizards]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[indeepgeek]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[highrollersdnd]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[arcanearcade]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[dndbeyond]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[dungeonsanddaddies]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[stinkydragonpod]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[pitchmeetings]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[pulpcomedy]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[julienolke]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[zacoyama]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[pitchmeetingshorts]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[ryangeorgeplus]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[idglive]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[acquisitionsincorporated]
incremental-interval = "P99999D"
complete-interval = "P99999D"

[taylortomlinsoncomedy]
incremental-interval = "P99999D"
complete-interval = "P99999D"
