[dropout]
incremental-interval = "PT4H"
recent-interval = "P7D"
recent-window = "P96D"
complete-interval = "P28D"

[dimension20show]
incremental-interval = "PT8H"
recent-interval = "P7D"
recent-window = "P96D"
complete-interval = "P40D"

[dimension20shorts]
incremental-interval = "PT8H"
recent-interval = "P7D"
recent-window = "P96D"
complete-interval = "P40D"

[umactually]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[gamechangershorts]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[makesomenoisedo]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[dirtylaundryshorts]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[veryimportantpeopleshow]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[thousandairesdo]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[dropoutpresents]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[smartypantsdropout]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[toonoutanimation]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[ParlorRoomShow]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[gastronautsshow]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[crowdcontroldo]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[nobodyaskedshow]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[monetsslumberparty]
incremental-interval = "PT8H"
recent-interval = "P14D"
recent-window = "P96D"
complete-interval = "P55D"

[loadingreadyrun]
incremental-interval = "P14D"
recent-interval = "P70D"
recent-window = "P96D"
complete-interval = "P140D"

[dorkly]
incremental-interval = "P70D"
complete-interval = "P350D"

[drawfee]
incremental-interval = "P56D"
complete-interval = "P280D"

[criticalrole]
incremental-interval = "P35D"
recent-interval = "P70D"
recent-window = "P96D"
complete-interval = "P350D"

