[dropout]
incremental-interval = "PT4M"
complete-interval = "P7D"

[dimension20show]
incremental-interval = "PT32M"
complete-interval = "P32D"

[dimension20shorts]
incremental-interval = "PT32M"
complete-interval = "P32D"

[umactually]
incremental-interval = "PT8H"
complete-interval = "P32D"

[gamechangershorts]
incremental-interval = "PT8H"
complete-interval = "P32D"

[makesomenoisedo]
incremental-interval = "PT8H"
complete-interval = "P32D"

[dirtylaundryshorts]
incremental-interval = "PT8H"
complete-interval = "P32D"

[veryimportantpeopleshow]
incremental-interval = "PT8H"
complete-interval = "P32D"

[thousandairesdo]
incremental-interval = "PT8H"
complete-interval = "P32D"

[dropoutpresents]
incremental-interval = "PT8H"
complete-interval = "P32D"

[smartypantsdropout]
incremental-interval = "PT8H"
complete-interval = "P32D"

[monetsslumberparty]
incremental-interval = "PT8H"
complete-interval = "P32D"

[rarran]
incremental-interval = "P2D"
complete-interval = "P128D"

[covertgoblue]
incremental-interval = "P2D"
complete-interval = "P128D"

[blueyofficialchannel]
incremental-interval = "P320D"
complete-interval = "P8D"

[deepblueink]
incremental-interval = "P40D"
complete-interval = "P128D"

[worldsbeyondnumber]
incremental-interval = "P120D"
complete-interval = "P128D"

[samreich]
incremental-interval = "P120D"
complete-interval = "P128D"

[blueyfrancais]
incremental-interval = "P160D"
complete-interval = "P128D"

["$blueycanada"]
incremental-interval = "P320D"
complete-interval = "P320D"

[naddpod]
incremental-interval = "P320D"
complete-interval = "P128D"

[screenrantplus]
incremental-interval = "P570D"
complete-interval = "P128D"

[geek_peek]
incremental-interval = "P580D"
complete-interval = "P128D"

[thejordonbrown]
incremental-interval = "P590D"
complete-interval = "P128D"

[loadingreadyrun]
incremental-interval = "P600D"
complete-interval = "P2600D"

[characterswelcome]
incremental-interval = "P610D"
complete-interval = "P2610D"

[dorkly]
incremental-interval = "P620D"
complete-interval = "P2620D"

[thewelltoldtale]
incremental-interval = "P630D"
complete-interval = "P2630D"

[drawfee]
incremental-interval = "P640D"
complete-interval = "P2640D"

[roll20app]
incremental-interval = "P650D"
complete-interval = "P2650D"

[criticalrole]
incremental-interval = "P660D"
complete-interval = "P2660D"

[siblingrivalrypodcast]
incremental-interval = "P670D"
complete-interval = "P2670D"

[hankschannel]
incremental-interval = "P680D"
complete-interval = "P2680D"

[rickastleyyt]
incremental-interval = "P690D"
complete-interval = "P2690D"

[geekandsundry]
incremental-interval = "P700D"
complete-interval = "P2700D"

[themcelroyfamily]
incremental-interval = "P710D"
complete-interval = "P2710D"

[briandavidgilbert]
incremental-interval = "P760D"
complete-interval = "P2760D"

[dndwizards]
incremental-interval = "P770D"
complete-interval = "P2770D"

[indeepgeek]
incremental-interval = "P790D"
complete-interval = "P2790D"

[highrollersdnd]
incremental-interval = "P800D"
complete-interval = "P2800D"

[arcanearcade]
incremental-interval = "P810D"
complete-interval = "P2810D"

[dndbeyond]
incremental-interval = "P820D"
complete-interval = "P2820D"

[dungeonsanddaddies]
incremental-interval = "P830D"
complete-interval = "P2830D"

[stinkydragonpod]
incremental-interval = "P840D"
complete-interval = "P2840D"

[pitchmeetings]
incremental-interval = "P850D"
complete-interval = "P2850D"

[pulpcomedy]
incremental-interval = "P860D"
complete-interval = "P2860D"

[julienolke]
incremental-interval = "P870D"
complete-interval = "P2870D"

[zacoyama]
incremental-interval = "P880D"
complete-interval = "P2880D"

[pitchmeetingshorts]
incremental-interval = "P890D"
complete-interval = "P2890D"

[ryangeorgeplus]
incremental-interval = "P900D"
complete-interval = "P2900D"

[idglive]
incremental-interval = "P910D"
complete-interval = "P2910D"

[acquisitionsincorporated]
incremental-interval = "P920D"
complete-interval = "P2920D"

[taylortomlinsoncomedy]
incremental-interval = "P940D"
complete-interval = "P2940D"
