name: Deno

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test --allow-none --allow-all

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

  # publish:
  #   needs: test
  #   if: github.ref == 'refs/heads/trunk'

  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read
  #     id-token: write

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Publish package
  #       run: npx jsr publish
